### ISSUE TITLE
Regression: source code isn't highlighted after gist load

### ISSUE THREAD

**Issue by smacker** [bblfsh/dashboard#102]
Most probably it got broken during redux refactoring.

**Comment by smacker** [comment]
Hm. I can't reproduce it in master branch.
But I saw bug during presentation.

@dpordomingo could you please try with that binary which you used and master branch?

**Comment by smacker** [comment]
@dpordomingo

**Comment by dpordomingo** [comment]
strange.
I tried with https://drive.google.com/file/d/125uZvbl0P-x6Bk9QUzK5UKMV4xu8UrdT/view and I could not reproduce the bug (I could not even see the gist).
I tried with the current tip of `master` (6e77f41) and I could not reproduce the bug &rarr; everything went ok.

Feel free to reopen if you have more details to reproduce the problem :dagger:
