### ISSUE TITLE
Improve accessibility of node hover color

### ISSUE THREAD

**Issue by marnovo** [bblfsh/dashboard#116]
The light-gray hover whenever you hover a node block on the UAST panel on the right is hard to notice in some screens (and/or for some visually impaired people), in contrast to the more obvious yellow color that shows up in the left side.
<img width="1680" alt="screen shot 2018-01-15 at 1 33 38 pm" src="https://user-images.githubusercontent.com/15906764/34949984-e9210e92-f9f8-11e7-8560-f75220e25640.png">

A few solution ideas:
- Change the intensity of the hover color.
- Change the hover color to a different one that helps matching visually the corresponding code on the other panel (keeping both contents visible).
- Add a border element to the hovered code/node block that is highlighted.

@ricardobaeta may have more interesting solutions.

**Comment by ricardobaeta** [comment]
@bzz @marnovo 

I think it's a pretty straightforward & quick solution. We can/should keep the colour scheme simple and apply the same colour - #ffff00 - but with a **very** soft Tint variation. 

I would go with the [smoother Tint of #ffff00](http://www.color-hex.com/color/ffff00) 

I've looked at the code, and I believe the hot-fix would be something like:

**.eckLzy** {
   ~~background: #f9f9f9;~~ 
   background: #ffffe5;
}

**Comment by marnovo** [comment]
@ricardobaeta can you please provide a screenshot with a before/after and tag the users here for a quick validation (Vadim, Alex, Egor, Eiso) before we push this? Thanks.

**Comment by ricardobaeta** [comment]
@vmarkovtsev @bzz @eiso @EgorBu 

**Before**

![image](https://user-images.githubusercontent.com/1746146/35121943-19f5ca00-fc95-11e7-8d04-230baa2be5a7.png)


**After**

![image](https://user-images.githubusercontent.com/1746146/35121880-e491b96e-fc94-11e7-8f0c-ab72eaca5d63.png)

**Comment by eiso** [comment]
Awesome, thank you
