### ISSUE TITLE
Extract uast viewer component to a lib

### ISSUE THREAD

**Issue by smacker** [bblfsh/dashboard#129]
We want to reuse it in other projects.

Scope:
- [x] Port UI to normal react components instead of styled components used in dashboard (to allow UI customization without dependency on styled components)
- [x] UAST viewer component with collapsing/hover
- [x] Controlled mode for UAST viewer to be able to manipulate uast in an application without losing user state.
- [x] UAST viewer + code editor with (hover of code should highlight node and vice versa)

**Comment by smacker** [comment]
Very basic lib: https://github.com/smacker/uast-viewer

It contains only presentation layer without any interaction (even hover).
Styled components were rewritten using normal components + sass.

Screenshots:
<img width="439" alt="screen shot 2018-05-10 at 19 22 52" src="https://user-images.githubusercontent.com/406916/39883636-c206ebd0-5487-11e8-9d95-de01609e5adf.png">

<img width="403" alt="screen shot 2018-05-10 at 19 23 13" src="https://user-images.githubusercontent.com/406916/39883643-c669c724-5487-11e8-85cf-e453882471a4.png">

**Comment by bzz** [comment]
@smacker please post a new use cases here.

**Comment by smacker** [comment]
Cases:
1. exactly the same as bblfsh dashboard (case isn't represented in wireframes)
2. when we have uast but don’t have code `select uast(content) from blobs`
3. when uast doesn’t much code `select uast(content, '/xpath'), content from blobs`
4. only code without uast (most probably we want to have the same editor as in case 1)

**Comment by smacker** [comment]
the lib was created. The dashboard uses it now. Closing.
