### ISSUE TITLE
Scroll code panel on UAST node click

### ISSUE THREAD

**Issue by bzz** [bblfsh/dashboard#136]
When clicking on the UAST node, only the highlight moves to the position in the Code, but not the scroll of the code panel. Sometimes, especially for long code examples (that we do not have in dashboard by default) it is quite had to follow, especially on the filtered UASTs.

This issue is about having a click on UAST node  scroll the relevant pice of  Code.

Most probably related to uast-viewer and thus can be shared between bblfsh dashboard and gitbase palyground.

**Comment by bzz** [comment]
As discussed IRL \w @smacker - other way around of focusing UAST on Code selection sounds as a great idea as well.

**Comment by smacker** [comment]
It feels kind of messy if I scroll code on hover of a node. Especially when I move the cursor from UAST to code, it goes through parent nodes and messes everything.

It's not defined when we should scroll code so I'll implement it on "click".
