### ISSUE TITLE
Enhance the expand nodes implementation

### ISSUE THREAD

**Issue by Serabe** [bblfsh/dashboard#31]

**Comment by erizocosmico** [comment]
Is not the expand nodes itself, but the indexing of nodes done using the react component instance itself in the index.

**Comment by marnovo** [comment]
@erizocosmico can you help me and @dpordomingo understand what was the issue? Thanks!

**Comment by erizocosmico** [comment]
@marnovo it's not like it's a pressing issue, this issue was just to remember that the whole node indexing thing was done with a React anti-pattern.

**Comment by dpordomingo** [comment]
thanks @erizocosmico for the clarification !

**Comment by marnovo** [comment]
To add the xpath feature #38, this is a necessary fix (as anything else that changes the tree).
