### ISSUE TITLE
Improve the documentation and readme

### ISSUE THREAD

**Issue by mcuadros** [bblfsh/dashboard#37]
We should explain the architecture, expand the README and add some screenshots.

**Comment by dpordomingo** [comment]
In the meantime here is a quick screenshot in case it can help someone; there is no extra/hidden info so it could may be useful for someone.
![image](https://user-images.githubusercontent.com/2437584/29172123-397a525e-7ddf-11e7-82ac-1f6ebe6db918.png)

**Comment by eiso** [comment]
Minor: 

`dashboard-server -bblfsh-addr=0.0.0.0:9432` to `dashboard-server --bblfsh-addr=0.0.0.0:9432`
