### ISSUE TITLE
Allow xpath searches

### ISSUE THREAD

**Issue by mcuadros** [bblfsh/dashboard#38]
We should allow xpath queries at the dashboard to be able to test and debug queries. A nice to have could be having a small xpath editor, to help the creation.

Requires having a client-go, still in planning phase.

/cc @abeaumont @juanjux @manucorporat

**Comment by marnovo** [comment]
Is the current state of `client-go` capable of this?

**Comment by eiso** [comment]
I really like this idea! 

@marnovo the python client just got this feature yesterday. I am not sure if the go client has it aswell.

**Comment by eiso** [comment]
It has been: https://github.com/bblfsh/client-go/pull/8/files

**Comment by zurk** [comment]
Yes, It will be really helpful. I need this feature.

**Comment by eiso** [comment]
Afaik @zork this has been implemented in both clients. @juanjux am I right?

**Comment by juanjux** [comment]
@eiso that's correct.

**Comment by smacker** [comment]
@ricardobaeta can you help us here?

**Comment by smacker** [comment]
the first version was implemented here: https://github.com/bblfsh/dashboard/pull/77#issuecomment-351731268
further improvements (like UX) will be done in separate issues.
