### ISSUE TITLE
Using Gist from Github

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/dashboard#46]
parent https://github.com/bblfsh/dashboard/issues/45

_As a user of the dashboard I want to be able to import a github gist directly to the input (left) panel, and to share that state_

It is needed to cover the following features:
- [x] Input text to specify which gist will be loaded into the left panel,
- [ ] A share button to share the dashboard with the gist already loaded into the input panel,
- [ ] The share button will copy into the browser clipboard a shareable gist url,
- [ ] If the dashboard is accessed through a shareable gist url, the gist url will be loaded into the input text, the gist content will be loaded into the input panel, and the gist UAST will be loaded into the right panel,

The shareable url will have the following format:
```
https://_DASHBOARD_HOST_NAME_/gist/mcuadros/89457425a26eeb8aa787538adb68acdb/raw/5067e3a8500645a259aa45794d614e0490926a37/ace-of-equinox.md
```

/cc @marnovo

**Comment by dpordomingo** [comment]
Hi @ricardobaeta I can not assign you to this issue, but I need a design for this feature.
Let me know if you need any other clarification.

**Comment by ricardobaeta** [comment]
Hey @dpordomingo 

Here you can find some solutions to the Dashboard needs, as well as the request design objectives.

![image](https://user-images.githubusercontent.com/1746146/30104525-c967db7a-92ed-11e7-9a82-bed9d62d8ae7.png)

![image](https://user-images.githubusercontent.com/1746146/30104539-d70befbe-92ed-11e7-8c97-32edaec8edff.png)

![image](https://user-images.githubusercontent.com/1746146/30104660-2bcd68d4-92ee-11e7-86e7-b260792b94ae.png)

![image](https://user-images.githubusercontent.com/1746146/30104674-366c1d08-92ee-11e7-99ae-33c0e9f362d6.png)


[babelfish-dashboard.pdf](https://github.com/bblfsh/dashboard/files/1280554/babelfish-dashboard.pdf)

**Comment by mcuadros** [comment]
In the minimal version of this feature:
- Should load only the gist from the a gist, but don't needs to upload the content. 
- When the content of a gist is loaded, cannot be edited (since you can't upload the content)
- Share button should just copy the URL to the clipboard, without additional screens.

**Comment by ricardobaeta** [comment]
Iteration upon feedback rationale.

![image](https://user-images.githubusercontent.com/1746146/30107399-8ef8520e-92f6-11e7-9893-4b985aedc59d.png)

![image](https://user-images.githubusercontent.com/1746146/30107413-98c4edce-92f6-11e7-92d8-9ffb92637379.png)

![image](https://user-images.githubusercontent.com/1746146/30107443-aed3e160-92f6-11e7-96a7-2bfd45b98084.png)

![image](https://user-images.githubusercontent.com/1746146/30107463-b8a5099e-92f6-11e7-99ef-0befd024adcf.png)

[babelfish-dashboard-two.pdf](https://github.com/bblfsh/dashboard/files/1280751/babelfish-dashboard-two.pdf)

**Comment by dpordomingo** [comment]
@ricardobaeta I do not understand the reason because the example dropdown was disabled when loading a gist.
Which is the purpose of the checkbox on the left side of the examples selector?
Why is disabled the examples selector after loading a gist?

The behavior I'd like (as a user) would be:
- enter the page -> example already loaded, and examples combo shows the loaded example,
- edit code, or load a gist -> the examples combo is changed to "load an example",
- I choose a new example from the combo -> it replaces the code in the left panel, to load the selected example.
No checkbox needed.

I think it is more simple and flexible, it isn't?

**Comment by dpordomingo** [comment]
The PR https://github.com/bblfsh/dashboard/pull/48 contains the «load from gist feature»; It still need tests and the url can not be shared yet. I hope to complete both in 1~2 working days

**Comment by ricardobaeta** [comment]
@dpordomingo I'm finishing writing a rationale about my decisions regarding https://github.com/bblfsh/dashboard/issues/46#issuecomment-327552331

**Comment by ricardobaeta** [comment]
Per discussed with @bzz further improvements will be address in different issues.
