### ISSUE TITLE
Quick changes

### ISSUE THREAD

**Issue by mcuadros** [bblfsh/dashboard#50]
- [x] Decrease font size a 20%
- [x] Move the "RUN Parser" to tthe right of screen
- [x] Add more example to the example combo: 
- [x] Use the same font in the text are and the tree: http://sourcefoundry.org/hack/
- [x] Remove the "Driver code" label from the octocat icon, and put "Driver repository" as an alt desc
- [x] Changes the example with the following files:

Name: `fizzbuzz.py`
```
def fizzbuzz(n):

    if n % 3 == 0 and n % 5 == 0:
        return 'FizzBuzz'
    elif n % 3 == 0:
        return 'Fizz'
    elif n % 5 == 0:
        return 'Buzz'
    else:
        return str(n)

print "\n".join(fizzbuzz(n) for n in xrange(1, 21))
```

Name: `classdef.py`
https://github.com/bblfsh/python-driver/blob/master/tests/classdef.py.source

Name: `hello.java`
```
// hello.java
import java.io.*;
import javax.servlet.*;

public class Hello extends GenericServlet {
    public void service(final ServletRequest request, final ServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html");
        final PrintWriter pw = response.getWriter();
        try {
            pw.println("Hello, world!");
        } finally {
            pw.close();
        }
    }
}
```

Name: `swap.java`
```
public class SwapElementsExample {
 
        public static void main(String[] args) {
               
                int num1 = 10;
                int num2 = 20;
               
                System.out.println("Before Swapping");
                System.out.println("Value of num1 is :" + num1);
                System.out.println("Value of num2 is :" +num2);
               
                //swap the value
                swap(num1, num2);
        }
 
        private static void swap(int num1, int num2) {
               
                int temp = num1;
                num1 = num2;
                num2 = temp;
               
                System.out.println("After Swapping");
                System.out.println("Value of num1 is :" + num1);
                System.out.println("Value of num2 is :" +num2);
               
        }
}
```

**Comment by dpordomingo** [comment]
On it.
I'll mark each subtask as "done" when it is ready in my dev machine, and I'll close the issue when the PR https://github.com/bblfsh/dashboard/pull/51 is merged

**Comment by dpordomingo** [comment]
as requested irl, I'll add to the changes:
- Remove the "Driver code" label from the octocat icon, and put "Driver repository" as an alt desc

**Comment by dpordomingo** [comment]
@mcuadros PR is ready to review 
https://github.com/bblfsh/dashboard/pull/51

**Comment by dpordomingo** [comment]
Merged and shipped into the new release https://github.com/bblfsh/dashboard/releases/tag/v0.1.2
