### ISSUE TITLE
Error with latest server version

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/dashboard#52]
As reported by @eiso via slack:
> I just pulled the latest server and I am getting the following error when trying to parse Python code from the dashboard: `
error parsing UAST: rpc error: code = Unimplemented desc = unknown service gopkg.in.bblfsh.sdk.v0.protocol.ProtocolService
`

**Comment by dpordomingo** [comment]
As pointed by @abeaumont vía Slack
> that error indicates that the client in the dashboard has not been updated to `v1` of the SDK... which makes sense because we didn't do it...

**Comment by mcuadros** [comment]
Fixed by https://github.com/bblfsh/dashboard/commit/41d3c91f3295558ec94d24749ccb6026c4be7dce
