### ISSUE TITLE
Vertical scroll on UAST window disappear under certain right widow sizes

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/dashboard#55]
Vertical scroll on UAST panel disappear under certain right panel and window sizes and when UAST is quite deep. When it happens, the UAST panel can be scrolled only with the mouse wheel.

![bblfshscroll](https://user-images.githubusercontent.com/2437584/30690791-a1c633c6-9ec5-11e7-965e-c463895971b2.png)

I could not reproduce it in the original https://astexplorer.net

**Comment by smacker** [comment]
fixed.
