### ISSUE TITLE
Do not "auto-parse" when user changes the language

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/dashboard#60]
@smeruelo suggested _irl_:
Do not "auto-parse" when user changes the language, otherwise it rises errors that can be expected but annoying.

### steps to reproduce the errors:
1. go to the dashboard,
2. change the language -> annoying errors!!!

or...
1. go to the dashboard,
2. write python code, 
3. change the language to Python -> everything goes good
4. change the language to Java again -> annoying errors!!!

**Comment by dpordomingo** [comment]
@marnovo could you confirm if we should address this enhancement? or should we keep the current behavior.

**Comment by smacker** [comment]
it's very useful feature when you have gist. I'll add more context later.

**Comment by dpordomingo** [comment]
Since bblfsh can guess the language of a file, we may use that feature when loading gist instead.
It may be useful to consider whether the most likely use case are the ones described in the issue desc, or changing the language after fetching a new gist.

**Comment by smacker** [comment]
I have another idea. How about we disable language selectbox if code was parsed successfully? Like if it parsed python code correctly, it won't be able to parse the same code with java driver.
I see only one problem js/ts. It can be JS code, but you want to parse it with ts driver. (but we don't have any of them right now)

**Comment by dpordomingo** [comment]
I think we need to analyze the problem from a UX point of view.
Make sense to auto-parse the code when the user changes the language?
There may be many scenarios when the user might want to change the language before writing new code in the new language, so he will receive a big and unexpected error.

Since the auto-parse on language change was not an initial dashboard requirement, the fastest and cheaper workaround would be to rollback [that feature](https://github.com/bblfsh/dashboard/pull/57/files#diff-14b1e33d5bf5649597cdc0e4f684daddR145), and avoid that errors until that behavior has been reconsidered and better defined.

**Comment by bzz** [comment]
\cc @ricardobaeta

**Comment by ricardobaeta** [comment]
> Make sense to auto-parse the code when the user changes the language?

We have the "Run Parser" button for a reason :)
