### ISSUE TITLE
Fix dashboard url in project description

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/dashboard#61]
Dashboard does not work with `https`, so the link should be fixed because it points to https://dashboard.bblf.sh -> `443: Connection timed out`
![image](https://user-images.githubusercontent.com/2437584/32557730-44c41004-c4a3-11e7-830c-ec25695186bf.png)

**Comment by campoy** [comment]
This has been fixed already.

**Comment by dpordomingo** [comment]
thanks for letting me know about the fix :dancer:
