### ISSUE TITLE
Rename dashboard to playground

### ISSUE THREAD

**Issue by campoy** [bblfsh/dashboard#62]
A dashboard shows metrics of the current status of a server, e.g. the [Kubernetes Dashboard](https://github.com/kubernetes/dashboard).

A playground allows a user to interact with a service without having to install anything first, e.g. [Go playground](play.golang.org) or the [Google API Playground](https://developers.google.com/oauthplayground/)

This repo implements a playground, and as such should be renamed to bblfs/playground.

**Comment by dpordomingo** [comment]
I agree with that rationale; The "dashboard" was initially considered under something closer to the real definition of "dashboard" (to let the user query the installed drivers, install new ones, statics...) but since the current state of the repo does not allow to do such things, I think it's sensible to rename it to "playground"

**Comment by campoy** [comment]
Cool, I think we need @mcuadros superpowers in order to make this happen?

**Comment by marnovo** [comment]
The naming rationale proposed by @campoy is indeed sensible.

@dpordomingo, can you quickly estimate (just a ballpark number) how much work renaming the project would entail, given the deployed online version, provided docker images, documentation here and in the bblfsh org, and more I might be forgetting?

Depending on the estimates we may add it to the next Applications sprint.

**Comment by dpordomingo** [comment]
I'd say than less than half day for sure. It may be 1h but I couldn't guarantee that.

**Comment by marnovo** [comment]
Sounds fair.

@mcuadros please let us know.

**Comment by mcuadros** [comment]
As I said in person when he suggested the idea, currently its true that the panel doesn't contain any information about the status of the server. But it-s because is not done, but should be done. And in this case fully qualified dashboard. So I rather not chaing it to a playground

**Comment by campoy** [comment]
Then the problem I see is that a dashboard and a playground have completely different audiences in mind.
Why are we providing a playground functionality (useful for demos) in a dashboard (useful for production monitoring)?

**Comment by mcuadros** [comment]
why you consider different audience? you don;'t want to see which drivers are installed? or update it? and after this test it? and explore how they work? 

This tool (with the driver managing) will be used more for testing and research than in production. 

I don't see any reason to build two application, adding more words to the lingo making harder to the people understand the project.

**Comment by campoy** [comment]
I see the playground as a completely serverless experience of what babelfish can deliver.
It's not about managing the resources on the server (that'd be the dashboard) but to try the project.

Maybe the playground can be simply one of the features in the dashboard. I'd be ok with that too.

If we were to expose babelfish as an API, I'd like the playground to be something that could be built atop of that API without any knowledge of what actually goes one in the servers or what drivers are currently installed.

**Comment by mcuadros** [comment]
The dashboard is not a severless thing is something to run with your installation, with the drivers that you have installed, and your server. 

Ok, I see, we can call playground to a dashboard version, not autheticated (or without write access). Basically means renaming the DNS to playground.bbl.sh.

But the code is the same. And the project it selft contains all the functionallity.

**Comment by campoy** [comment]
Deal, let's try to get a non authenticated, read-only, instance of bblfsh under play.bblf.sh then.
Created #75 to track the effort
