### ISSUE TITLE
metrics from Dashboard --> Google Analytics

### ISSUE THREAD

**Issue by gomesfernanda** [bblfsh/dashboard#63]
We need to gather Dashboard metrics on Google Analytics regarding audience (visits, time spent etc). I believe this is strongly related to @dpordomingo. Please let me know if you need further details.

**Comment by dpordomingo** [comment]
So, if no other info is provided, it'd be done with the GA default configuration.
```javascript
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-69608223-1', 'auto');
    ga('send', 'pageview');
</script>
```

Should we use certain GA tracker?
should we use the landing one `UA-69608223-1`? (I don't think so)

**Comment by gomesfernanda** [comment]
I don't think we should use the landing tracker.
I created a new tracker for the Dashboard: `UA-69608223-6`

__Website Tracking - Global Site Tag__
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-69608223-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-69608223-6');
</script>
```

Also, if we can track the clicks on the links available on the dashboard, it can be useful in the future.
[https://github.com/bblfsh](https://github.com/bblfsh)
[https://doc.bblf.sh/](https://doc.bblf.sh/)
[http://codemirror.net/](http://codemirror.net/)
[https://facebook.github.io/react](https://facebook.github.io/react)
[https://github.com/bblfsh/dashboard/#fork-destination-box](https://github.com/bblfsh/dashboard/#fork-destination-box)
[https://sourced.tech/](https://sourced.tech/)

Let me know if there's any other info you need @dpordomingo ! :)

(ccing @campoy)

**Comment by dpordomingo** [comment]
For estimation purposes:
- Adding the default tracker -> quick, safe and easy,
- hijacking and tracking some links -> not that quick, not that safe, not that easy (but feasible as it is done in Landing)

**Comment by gomesfernanda** [comment]
so I believe we should first implement the default tracker, so we can start monitoring as soon as possible, and then we study the need/implementability of link tracking.
waiting for @marnovo input on this.

Thanks!

**Comment by marnovo** [comment]
Questions mostly about the lingo (synthesized answers please):
1. What does `default tracker` mean under this context?
2. What is the added benefit of the `hijacking & tracking` over it?
3. What are we using in the landing, blog?
4. What is the difference in terms of work for each approach?

**Comment by campoy** [comment]
And an extra question from my side: why are we using different tracking accounts rather than adding info to the events we fire?

I wonder if it'd be easier to get a global view of the visits across domains that way

Actually I'd advocate for one account per domain:
- sourced.tec
- bblfsh.sh
- any others?

**Comment by gomesfernanda** [comment]
> 1. What does default tracker mean under this context?

the one available on Google Analytics instructions:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXXX-X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXXXX-X');
</script>
```

> 2. What is the added benefit of the hijacking & tracking over it?

We have metrics on clicks on each external link, not only "drop-off"s (as GA current labels) and buttons, so we can analyze the efficiency of them and how they're placed on the pages.

> 3. What are we using in the landing, blog?

On the landing we track the clicks on "Join our Slack" button and on external links. We don't have a distinction, however, which external link was clicked (it's just labeled "outbound").
On "talks" we have inbound/outbound metrics, and on blog we have no events implemented.

> 4. What is the difference in terms of work for each approach?

I can't answer this, since this last implementation (clicks on external links and Slack button) was done by Sergio and I wasn't aware of the process itself. (I believe @marnovo can add info on this)

> 5. (@campoy) Why are we using different tracking accounts rather than adding info to the events we fire?

When I was added to GA, we had the account `source{d}`, and under it we had the properties `talks`, `landing`, `blog`, `alpha` and `Lever`. I created 2 more: one for our `GitHub repos` (that we're implementing tracking pixel) and one for the `Babelfish` dashboard. I believe that this is efficient to distinguish the source of the audience, and we can use the features on datastudio to sum up the audience metrics that are convenient to us, according to our discretion.

**Comment by mcuadros** [comment]
This is not the place to speak about this, also @eiso and me We don't belive of tracking this things, since we don't do open source for take a benefit.

Also this is related about the deployment it self and not the project. Obvously we are not going to add this metric to every on-premise deployment.

If you need track something, tracking from the logs. 

Sorry.
