### ISSUE TITLE
Latest dashboard fails to communicate with latest server

### ISSUE THREAD

**Issue by campoy** [bblfsh/dashboard#64]
In a freshly installed macbook I'm running these commands (following the documentation) and seeing errors.

```bash
> docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd
81f1bb5453b9074185ace4afd2c34a2c7e5ea74931ee507bc08b2999565ecdb9

> docker exec -it bblfshd bblfshctl driver install --all
Installing python driver language from "docker://bblfsh/python-driver:latest"... Done
Installing java driver language from "docker://bblfsh/java-driver:latest"... Done

> docker run -p 8080:80 --link bblfshd bblfsh/dashboard -bblfsh-addr bblfshd:9432
time="2017-11-10T17:09:27Z" level=info msg="starting REST server" addr=":80"
```

After running these commands my docker client has two images:

```bash
> docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bblfsh/bblfshd      latest              7379a3cad7ac        2 weeks ago         170MB
bblfsh/dashboard    latest              c301a8651163        7 weeks ago         25.7MB
```

Then when I try to access the local dashboard running on localhost:8080 and click on "run parser" I get this error:

```
Error
error parsing UAST: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: wrong wireType = 0 for field InternalType
```

![screen shot 2017-11-10 at 6 10 10 pm](https://user-images.githubusercontent.com/2237452/32669933-79db3736-c642-11e7-87a1-5f67b4c71829.png)

More logs below:

<details>
Logs from the dashboard:
<pre>
time="2017-11-10T17:09:27Z" level=info msg="starting REST server" addr=":80"
time="2017-11-10T17:10:01Z" level=info msg="[GIN] 2017/11/10 - 17:10:01 | 200 |     388.962µs |      172.17.0.1 | GET      /api/drivers"
time="2017-11-10T17:10:04Z" level=info msg="[GIN] 2017/11/10 - 17:10:04 | 500 |  1.576631479s |      172.17.0.1 | POST     /api/parse"
</pre>

Logs from bblfhsd:
<pre>
time="2017-11-10T17:07:36Z" level=info msg="bblfshd version: v2.1.2 (build: 2017-10-26T10:53:53+0000)"
time="2017-11-10T17:07:36Z" level=info msg="initializing runtime at /var/lib/bblfshd"
time="2017-11-10T17:07:36Z" level=info msg="control server listening in /var/run/bblfshctl.sock (unix)"
time="2017-11-10T17:07:36Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"
time="2017-11-10T17:08:28Z" level=info msg="driver python installed "bblfsh/python-driver:latest""
time="2017-11-10T17:08:54Z" level=info msg="driver java installed "bblfsh/java-driver:latest""
time="2017-11-10T17:10:03Z" level=info msg="java-driver version: dev-8a99b6f (build: 2017-11-10T16:21:02Z)" id=01bykehtdhjd4jsytrqt8mkk1p language=java
time="2017-11-10T17:10:03Z" level=info msg="server listening in /tmp/rpc.sock (unix)" id=01bykehtdhjd4jsytrqt8mkk1p language=java
time="2017-11-10T17:10:04Z" level=info msg="new driver instance started bblfsh/java-driver:latest (01bykehtdhjd4jsytrqt8mkk1p)"
</pre>
</details>

**Comment by dpordomingo** [comment]
Wow... many thanks for the detailed explanation!

**Comment by dpordomingo** [comment]
... so sad.
I'm pretty sure that it will work if you try running the dashboard with the following:
```shell
docker run -p 8080:80 --link bblfshd bblfsh/dashboard:v0.3.0 -bblfsh-addr bblfshd:9432
```

As you saw, I just added the tag v0.3.0 to the dashboard image.
Let me know if it solved your problem.

I described the problem in the new issue https://github.com/bblfsh/dashboard/issues/65

**Comment by dpordomingo** [comment]
@mcuadros could you update the `:latest` tag, pointing to the `v0.3.0` tag?

**Comment by mcuadros** [comment]
why me? do it yourself. :)

**Comment by campoy** [comment]
Do I have those superpowers already? 😮 
Also, I'm assuming that's a SGTM from you?

**Comment by mcuadros** [comment]
Is for David, the CI should do this every-time that a new image is pushed, otherwise this will be a temporal fix.  hehe

**Comment by mcuadros** [comment]
I just tagged v0.3.0 as new latest

**Comment by dpordomingo** [comment]
Problem with current `:latest` image was manually solved.
The problem with the CI will be tracked in the separated issue https://github.com/bblfsh/dashboard/issues/65
