### ISSUE TITLE
bblfsh/dashboard:latest tag is not updated when released a new tag

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/dashboard#65]
It seems that [`ci/Makefile.main`](https://github.com/src-d/ci/blob/master/Makefile.main) `docker-push` rule does not update the `:latest` tag when a new tag is updated, does it?

If that's true, it's a pity because when locally installing the dashboard, it is used the [`bblfsh/dashboard:latest` tag from DockerHub](https://hub.docker.com/r/bblfsh/dashboard/tags/)

blocked by https://github.com/src-d/ci/issues/44

**Comment by bzz** [comment]
Shall we merge https://github.com/bblfsh/dashboard/issues/45 and push v0.4.0 to dockerhub?

**Comment by dpordomingo** [comment]
Nope: the numbered tag is automatically pushed by the CI when a release is tagged.
What would be missing is the `:latest` tag, that should be manually created an pushed to dockerhub; it can be done only by @mcuadros (as far as I remember). To automate that last thing, it should be merged https://github.com/src-d/ci/pull/44

**Comment by smacker** [comment]
It was fixed by https://github.com/bblfsh/dashboard/pull/100 and https://github.com/src-d/ci/pull/47
