### ISSUE TITLE
Everything broke spectacularly when I switched from Java to Python

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/dashboard#80]
I opened `dashboard.bblf.sh`, clicked the dropdown and selected Python. Everything has exploded:
![image](https://user-images.githubusercontent.com/2793551/33875766-ac4bfc88-df23-11e7-9d73-ece100c5589e.png)

**Comment by bzz** [comment]
Seems like it's due to https://github.com/bblfsh/dashboard/issues/60 and @smacker has proposed the solution https://github.com/bblfsh/dashboard/issues/60#issuecomment-348677439 that might be included in further sprints.

**Comment by smacker** [comment]
as a workaround for now: type some valid python and then change language.
we need to think more about how to fix it. In terms of UX. Maybe we need to add button to clear code or something else.

I close issue as a duplicate, but we will fix it as soon as have good solution and time to implement it.
