### ISSUE TITLE
Hovering on a Python function

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/dashboard#81]
I hover over "Node" and this is what I see:

![screenshot from 2017-12-12 10-12-03](https://user-images.githubusercontent.com/2793551/33876221-2f04d0d6-df25-11e7-871e-33539113ee87.png)

There are two problems IMHO:

1. If I hover over the empty area right to "Node" then `:hover` is still activated. Looks like the size of the element does not match the string value.
2. The last "z" in "fizzbuzz" is not highlighted.

**Comment by smacker** [comment]
thank you for bug report!

1) I suppose it was intended to work like that, but we will think about it again.
2) It's known bug. We need to investigate is it a bug in dashboard or driver https://github.com/bblfsh/dashboard/issues/68

**Comment by vmarkovtsev** [comment]
Regarding (1), David explained to me why in the kitchen. If I saw a frame around the whole block, I would understand this behavior.

**Comment by smacker** [comment]
@vmarkovtsev do you think if we add such background on hover it would be helpful?
https://drive.google.com/file/d/1M7LbJGVjnPg32I9iAeYrzbiPcwnRko0Y/view?usp=sharing

(I used background instead of border frame because it looks ugly)

**Comment by vmarkovtsev** [comment]
Can be only my eyes but I barely see the box. Yet it helps much, cool.
