### ISSUE TITLE
Is `make serve` target really working?

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/dashboard#83]
I tried twice and it failed, and only worked after running `yarn start`; I think the assets are not properly generated -> served by the api one it is ran `make serve`

**Comment by smacker** [comment]
what was the error exactly? Looks like it works fine for me:
```
git clean -ffdx
make serve
```

After that I can open http://localhost:9999/ with latest version of static.

**Comment by dpordomingo** [comment]
I'lo try to reproduce it properly. I had it a couple of different times.
