### ISSUE TITLE
Tests for non-success cases print errors in console

### ISSUE THREAD

**Issue by smacker** [bblfsh/dashboard#86]
We have some `console.error` statements in code (for example in api).
When we run tests for non-success cases you can see errors in report. It's confusing.
We need to find a way how to avoid it. For now I see 3 options:
1) remove console.error from code
2) mock console in tests
3) use error sender wrapper in code (it will be console.error in prod/dev for now and noop-func in tests)

**Comment by dpordomingo** [comment]
You ordered by cost ASC, power/flexibility DESC. ;)
If we choose (1) we lose error traceability.
If I understood you, (2) could be done as an intermediate step of (3), so if we start with (2) and we later need (3), we could reuse the work done for (2).
If so, I'd vote for (2)

**Comment by smacker** [comment]
not exactly. mocking usually means `beforeEach(() => mockSomething)` on very top. And when we mock console, we can break it somewhere in jest or so.

For a wrapper it would look something like:
```js
logger.js:

const consoleLogger = ...;
const noopLogger = ...;
const prettyLogger = ...;

export default function() {
  switch (proccess.env) {
    case 'TEST': return  noopLogger;
    case 'DEV': return prettyLogger;
    default: return consoleLogger;
  }
}

**Comment by dpordomingo** [comment]
You're right. Mocking `Global.console` for testing can break something in jest.
3rd option seems to be secure enough
