### ISSUE TITLE
Recover driver list from gRPC and not have a fixed list

### ISSUE THREAD

**Issue by mcuadros** [bblfsh/dashboard#89]
We should recover the list of driver installed on the server and the versions, instead of the hardcoded list.

**Comment by smacker** [comment]
Do you think we should add method to `client-go` or call bblfshd gRPC directly from dashboard?

**Comment by mcuadros** [comment]
The better will be call to gRPC: https://godoc.org/github.com/bblfsh/bblfshd/daemon/protocol, otherwise you will need to parse an ASCII table. 

In this case we will need use `dep` because this API is not versioned.

**Comment by smacker** [comment]
Let's wait for decision about this proposal first: https://github.com/bblfsh/client-go/pull/32

**Comment by bzz** [comment]
As soon as  bblfsh/client-go#32 is merged now and before adding new drivers at #119 let's move forward with this.

For strange reason I do not have enough permissions for this repo to manage labels, @mcuadros could you please kindly help, adding right permissions bits?

Meanwhile @dpordomingo would you mind adding it to Applications project, so it shows up on our backlog? Thanks in advance!

**Comment by dpordomingo** [comment]
@bzz done
(and added some context with related issues at https://github.com/bblfsh/dashboard/issues/119#issuecomment-376847056)
